import type { ExtraConfig } from '@shared/types'
import { DEFAULT_BINDINGS } from '@shared/types'
import { ICON_120_B64, ICON_180_B64, ICON_256_B64 } from '@shared/assets/carIcons'
import { HandDriveType, MicType, PhoneWorkMode } from '@shared/types/DongleConfig'

export const DEFAULT_EXTRA_CONFIG: ExtraConfig = {
  width: 800,
  height: 480,
  fps: 60,
  projectionSafeAreaTop: 0,
  projectionSafeAreaBottom: 0,
  projectionSafeAreaLeft: 0,
  projectionSafeAreaRight: 0,
  projectionSafeAreaDrawOutside: true,
  naviWidth: 800,
  naviHeight: 480,
  naviFps: 60,
  naviSafeAreaTop: 0,
  naviSafeAreaBottom: 0,
  naviSafeAreaLeft: 0,
  naviSafeAreaRight: 0,
  naviSafeAreaDrawOutside: false,
  lastPhoneWorkMode: PhoneWorkMode.CarPlay,
  apkVer: '2025.03.19.1126',
  carName: 'LIVI',
  oemName: 'App',
  nightMode: 'dark',
  hand: HandDriveType.LHD,
  mediaDelay: 1000,
  mediaSound: 1,
  callQuality: 1,
  autoConn: true,
  UseBTPhone: false,
  audioTransferMode: false,
  dashboardMediaInfo: true,
  dashboardVehicleInfo: true,
  dashboardRouteInfo: true,
  gps: false,
  gnssGps: false,
  gnssGlonass: false,
  gnssGalileo: false,
  gnssBeiDou: false,
  wifiType: '5ghz',
  wifiChannel: 36,
  micType: MicType.CarMic,
  phoneConfig: {},
  startPage: 'home',
  language: 'en',
  kiosk: true,
  uiZoomPercent: 100,
  camera: '',
  cameraMirror: false,
  autoSwitchOnStream: false,
  autoSwitchOnPhoneCall: true,
  autoSwitchOnGuidance: true,
  dongleToolsIp: '',
  visualAudioDelayMs: 120,
  audioVolume: 0.95,
  navVolume: 0.95,
  siriVolume: 0.95,
  callVolume: 0.95,
  primaryColorDark: '',
  highlightColorDark: '',
  primaryColorLight: '',
  highlightColorLight: '',
  mapsEnabled: false,
  telemetryEnabled: false,
  telemetryDashboards: [],
  bindings: DEFAULT_BINDINGS,
  dongleIcon120: ICON_120_B64,
  dongleIcon180: ICON_180_B64,
  dongleIcon256: ICON_256_B64
}
